name: FM-index-profile-time

on:
  push:
    branches:
      - master
      - develop
      - "feature/**"
      - "release/**"
      - "hotfix/**"
    tags:
      - "time-**/cpu"
      - "time-**/parallel"
      - "time-**/gpu"
    paths:
      - "fmindex/**"
      - "!fmindex/docs/**"
      - "!fmindex/**.md"

jobs:
  build:
    name: Test Build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Building
        id: build
        uses: ./.github/actions/build
        if: success()
        with:
          target: fmindex
          cmake_build_type: Release

  time:
    name: Measure time
    needs: build
    runs-on: self-hosted
    strategy:
      max-parallel: 2
      matrix:
        size: [1000, 10000, 100000]
    steps:
      - name: Measure time
        id: measuretime
        uses: ./.github/actions/measure_runtime
        with:
          target: fmindex
          size: ${{ matrix.size }}

      - name: Get runtime
        if: success()
        run: echo "Radix sort runtime with ${{ matrix.size }} inputs was ${{ steps.measuretime.outputs.runtime }}"
